<a href="https://colab.research.google.com/github/agibayrashitnu/Deep-Learning/blob/main/Binary_classification_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install tensorflow-gpu

  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [ ]:
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.13.0


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Preprocessing the Data


In [ ]:
# importing the dataset
from google.colab import files
uploaded = files.upload()

Saving Churn_Modelling.csv to Churn_Modelling.csv


In [ ]:
print(uploaded)

In [ ]:
!ls

Churn_Modelling.csv  sample_data


In [ ]:
#Reading the dataset using Pandas
dataset = pd.read_csv("Churn_Modelling.csv")

In [ ]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
# Selecting Dependent and Intependent Variables
x = dataset.drop(labels = ['RowNumber', 'CustomerId', 'Surname', 'Exited'], axis = 1)
y = dataset.Exited

In [ ]:
x.head(10)

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   
5          645     Spain    Male   44       8  113755.78              2   
6          822    France    Male   50       7       0.00              2   
7          376   Germany  Female   29       4  115046.74              4   
8          501    France    Male   44       4  142051.07              2   
9          684    France    Male   27       2  134603.88              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10  
5          1               0        149756.71  
6          1               1         10062.80  
7          1               0        119346.88  
8          0               1         74940.50  
9          1               1         71725.73

In [ ]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [ ]:
# Encoding the categorical data
from sklearn.preprocessing import LabelEncoder


In [ ]:
label_1 = LabelEncoder()
x.Geography = label_1.fit_transform(x.Geography)

In [ ]:
x.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0  Female   42       2       0.00              1   
1          608          2  Female   41       1   83807.86              1   
2          502          0  Female   42       8  159660.80              3   
3          699          0  Female   39       1       0.00              2   
4          850          2  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [ ]:
label_2 = LabelEncoder()
x.Gender = label_2.fit_transform(x.Gender)

In [ ]:
x.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          2       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          2       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [ ]:
# Avoiding the dummy variables trap
x = pd.get_dummies(x, drop_first = True, columns= ["Geography"])
x.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Geography_1  Geography_2  
0               1        101348.88            0            0  
1               1        112542.58            0            1  
2               0        113931.57            0            0  
3               0         93826.63            0            0  
4               1         79084.10            0            1

In [ ]:
# Splitting the data into train and test split
from sklearn.model_selection import train_test_split

x_train, x_test , y_train, y_test = train_test_split(x,y, test_size = 0.2, random_state = 0)

In [ ]:
# Feature Scaling Process

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
x_train

array([[ 0.16958176, -1.09168714, -0.46460796, ...,  1.10643166,
        -0.5698444 ,  1.74309049],
       [-2.30455945,  0.91601335,  0.30102557, ..., -0.74866447,
         1.75486502, -0.57369368],
       [-1.19119591, -1.09168714, -0.94312892, ...,  1.48533467,
        -0.5698444 , -0.57369368],
       ...,
       [ 0.9015152 ,  0.91601335, -0.36890377, ...,  1.41231994,
        -0.5698444 , -0.57369368],
       [-0.62420521, -1.09168714, -0.08179119, ...,  0.84432121,
        -0.5698444 ,  1.74309049],
       [-0.28401079, -1.09168714,  0.87525072, ...,  0.32472465,
         1.75486502, -0.57369368]])

In [ ]:
x_test

array([[-0.55204276, -1.09168714, -0.36890377, ...,  1.61085707,
         1.75486502, -0.57369368],
       [-1.31490297, -1.09168714,  0.10961719, ...,  0.49587037,
        -0.5698444 , -0.57369368],
       [ 0.57162971, -1.09168714,  0.30102557, ..., -0.42478674,
        -0.5698444 ,  1.74309049],
       ...,
       [-0.74791227,  0.91601335, -0.27319958, ...,  0.71888467,
        -0.5698444 ,  1.74309049],
       [-0.00566991,  0.91601335, -0.46460796, ..., -1.54507805,
         1.75486502, -0.57369368],
       [-0.79945688,  0.91601335, -0.84742473, ...,  1.61255917,
         1.75486502, -0.57369368]])

# Building the Model

In [ ]:
# Creating an object ( Innitializin ANN)

model = tf.keras.models.Sequential()

In [ ]:
#Adding input layer and first hidden layer

#1) Number of units have to be specified units = 6 ( usually average of input and output (11+1)/2 = 6(just trick))
#2)Activation Function = ReLU
#3) input dimension = 11 ( number of columns that is being taken as input i.e independent variables)

model.add(tf.keras.layers.Dense(units = 6, activation = 'relu', input_dim = 11))

In [ ]:
x.shape

(10000, 11)

In [ ]:
# Adding Second hidden layer
model.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

In [ ]:
#Output Layer
model.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

In [ ]:
#Compiling the model
model.compile(optimizer = 'adam', loss= 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
#Params in first layer is equal to units* (input dim+1)
# Params in second layer = units* (units+1)
# params in last layer = units*(units+1)
# Total params = sum of all params
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 6)                 72        
                                                                 
 dense_1 (Dense)             (None, 6)                 42        
                                                                 
 dense_2 (Dense)             (None, 1)                 7         
                                                                 
Total params: 121 (484.00 Byte)
Trainable params: 121 (484.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


# Training the Model

In [ ]:
# x_train is numpy array and y_train is a vector, so we convert vector to numpy array
# batch size = 10 , epochs = 20 means we are passing the data into model 20 times and we pass it in batch of 10
model.fit(x_train,y_train.to_numpy(), batch_size = 10, epochs = 20)

Epoch 1/20
800/800 [==============================] - 2s 2ms/step - loss: 0.5490 - accuracy: 0.7346
Epoch 2/20
800/800 [==============================] - 2s 2ms/step - loss: 0.4349 - accuracy: 0.8123
Epoch 3/20
800/800 [==============================] - 2s 3ms/step - loss: 0.4203 - accuracy: 0.8200
Epoch 4/20
800/800 [==============================] - 2s 2ms/step - loss: 0.4148 - accuracy: 0.8234
Epoch 5/20
800/800 [==============================] - 1s 2ms/step - loss: 0.4099 - accuracy: 0.8276
Epoch 6/20
800/800 [==============================] - 1s 2ms/step - loss: 0.4055 - accuracy: 0.8266
Epoch 7/20
800/800 [==============================] - 1s 2ms/step - loss: 0.3996 - accuracy: 0.8275
Epoch 8/20
800/800 [==============================] - 1s 2ms/step - loss: 0.3932 - accuracy: 0.8314
Epoch 9/20
800/800 [==============================] - 1s 2ms/step - loss: 0.3861 - accuracy: 0.8344
Epoch 10/20
800/800 [==============================] - 1s 2ms/step - loss: 0.3786 - accuracy: 0.8440

# Model Evaluation and Prediction

In [ ]:
# Evaluation of the model
test_loss , test_acc = model.evaluate(x_test,y_test.to_numpy())

63/63 [==============================] - 0s 2ms/step - loss: 0.3421 - accuracy: 0.8560


In [ ]:
print(f"Test accuracy is: ", test_acc)

Test accuracy is:  0.8560000061988831


In [ ]:
y_pred = np.argmax(model.predict(x_test), axis=1)

63/63 [==============================] - 0s 2ms/step


In [ ]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
y_test

9394    0
898     1
2398    0
5906    0
2343    0
       ..
1037    0
2899    0
9549    0
2740    0
6690    0
Name: Exited, Length: 2000, dtype: int64

In [ ]:
# confusion_matrix
from sklearn.metrics import confusion_matrix, accuracy_score

cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1595    0]
 [ 405    0]]


In [ ]:
acc_cm = accuracy_score(y_test, y_pred)
print(acc_cm)

0.7975
